[workflow]
    1 = "Flux-tile放大-在线生图Flux-4K-极速版.json"
    2 = "修图api.json"
    3 = "827-印花提取(最终版).json"
    4 = "逆采样印花裂变api.json"
    5 = "抠图.json"
    6 = "印花提取.json"
    7 = "高清放大-api.json"
    8 = "换脸(女).json"
    9 = "Z-Image-Turbo-人像去Ai味真实质感.json"
    10 = "换装2.json"
    11 = "换脸(男).json"